spring.application.name=WebGuardX
server.port=1002

# MongoDB
spring.data.mongodb.uri=mongodb+srv://webguardx_user:Siddheshwar@cluster0.kyxzhiq.mongodb.net/webguardx?retryWrites=true&w=majority
#spring.data.mongodb.uri=mongodb+srv://siddheshwars2005_db_user:4ytCKt6DJhBRpxfR@cluster0.kyxzhiq.mongodb.net/webguardx?retryWrites=true&w=majority


# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# Optional logging
#logging.level.org.springframework.security=DEBUG


jwt.secret=webguardxsecretkeywebguardxsecretkeywebguardxsecretkey123456
jwt.expiration=3600000


#zap
zap.host=localhost
zap.port=8081
zap.api.key=a2n4q6ugs7ol05nmlsu6cbjdu4